/* Generated By:JJTree: Do not edit this line. ASTand.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTand extends SimpleNode {
  public ASTand(int id) {
    super(id);
  }

  public ASTand(Lang p, int id) {
    super(p, id);
  }

  public void run() throws Exception {
	  assert this.jjtGetNumChildren() == 2;
	  for (Node n : this.children) {
		  ((MyNode)n).run();
	  }
	  
	  Object v2 = MyNode.pop();
	  Object v1 = MyNode.pop();
	  
	  if (v1 instanceof Boolean && v2 instanceof Boolean) {
		  MyNode.push((Boolean)v1 && (Boolean)v2);  
	  } else {
		  throw new Exception("Internal type error");
	  }
  }
}
/* JavaCC - OriginalChecksum=1cbe9c5210ae6e435629db88eb1857ab (do not edit this line) */
