/* Generated By:JJTree: Do not edit this line. ASTargument.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTargument extends SimpleNode {
  public ASTargument(int id) {
    super(id);
  }

  public ASTargument(Lang p, int id) {
    super(p, id);
  }

  public void run() throws Exception {
	  if (this.jjtGetNumChildren() == 0) {
		  MyNode.push(this.value);
	  } else {
		  assert this.jjtGetNumChildren() == 1;
		  ((MyNode)this.jjtGetChild(0)).run();
	  }
  }
}
/* JavaCC - OriginalChecksum=7a36c54733ea2ddced2d71d1f072207e (do not edit this line) */
