/* Generated By:JJTree: Do not edit this line. ASTaffect.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

import java.util.HashMap;

public
class ASTaffect extends SimpleNode {
  public ASTaffect(int id) {
    super(id);
  }

  public ASTaffect(Lang p, int id) {
    super(p, id);
  }

  public void run() throws Exception {
	  HashMap<String, Variable> sym = get_context_here();
	  
	  String varname = (String)((SimpleNode)this.children[0]).value;
	  Variable var = sym.get(varname);
	  if (var == null)
		  throw new ParseException("Use of unknown variable "+varname);
	  
	  ((MyNode)this.jjtGetChild(1)).run();
	  
	  Object new_value = MyNode.pop();
	  if (new_value instanceof String)
		  var.setVal((String)new_value);
	  else
		  var.setVal(new_value);
  }
}
/* JavaCC - OriginalChecksum=8aa4b3183327dcc13b87bb19953e308e (do not edit this line) */
