/* Generated By:JJTree: Do not edit this line. ASTarith.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTarith extends SimpleNode {
  public ASTarith(int id) {
    super(id);
  }

  public ASTarith(Lang p, int id) {
    super(p, id);
  }
  
  public void run() {
	  try {
		  MyNode.push(Integer.parseInt((String) this.value));
	  } catch (NumberFormatException e ) {
		  MyNode.push(Float.parseFloat((String) this.value));
	  }
  }
  
}
/* JavaCC - OriginalChecksum=0628c01af134f52acdc81168d36879a8 (do not edit this line) */
