/* Generated By:JJTree: Do not edit this line. ASTbool.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTbool extends SimpleNode {
  public ASTbool(int id) {
    super(id);
  }

  public ASTbool(Lang p, int id) {
    super(p, id);
  }

  public void run() {
	  MyNode.push(Boolean.parseBoolean((String) this.value));
  }
}
/* JavaCC - OriginalChecksum=b65b220e6862e62544712f28febea3fd (do not edit this line) */
