/* Generated By:JJTree: Do not edit this line. ASTdeclarations.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTdeclarations extends SimpleNode {
  public ASTdeclarations(int id) {
    super(id);
  }

  public ASTdeclarations(Lang p, int id) {
    super(p, id);
  }

  public void run() throws Exception {  
	  for (Node n : this.children) {
		  ((MyNode)n).run(); //variable ou constant
	  }
  }
}
/* JavaCC - OriginalChecksum=9e1890117dbed0670480a9ac83405ffd (do not edit this line) */
