/* Generated By:JJTree: Do not edit this line. ASTident.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

import java.util.HashMap;

public
class ASTident extends SimpleNode {
  public ASTident(int id) {
    super(id);
  }

  public ASTident(Lang p, int id) {
    super(p, id);
  }

  public void run() throws Exception {
	  HashMap<String, Variable> sym = get_context_here();
	  
	  Variable v = sym.get(this.value);
	  if (v == null)
		  throw new Exception("Undefined symbol "+this.value);
	  if (v.getVal() == null)
		  throw new Exception("Attempted to use uninitialised variable "+this.value);
	  MyNode.push(v.getVal());
  }
}
/* JavaCC - OriginalChecksum=56b09caf9a1e8e587b37abd3b125346d (do not edit this line) */
