/* Generated By:JJTree: Do not edit this line. ASTinstructions.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTinstructions extends SimpleNode {
  public ASTinstructions(int id) {
    super(id);
  }

  public ASTinstructions(Lang p, int id) {
    super(p, id);
  }

  public void run() throws Exception {
	  for (Node n : this.children) {
		  ((MyNode)n).run(); 
	  }
  }
}
/* JavaCC - OriginalChecksum=7b938fb8a667c74c46add5834faa3125 (do not edit this line) */
