/* Generated By:JJTree: Do not edit this line. ASTmin.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTmin extends SimpleNode {
  public ASTmin(int id) {
    super(id);
  }

  public ASTmin(Lang p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b8ec1d4f8fbecba3e7425373c8a7d715 (do not edit this line) */
