/* Generated By:JJTree: Do not edit this line. ASTnot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTnot extends SimpleNode {
  public ASTnot(int id) {
    super(id);
  }

  public ASTnot(Lang p, int id) {
    super(p, id);
  }

  public void run() throws Exception {
	  assert this.jjtGetNumChildren() == 1;
	  ((MyNode)this.children[0]).run();
	  
	  Object v1 = MyNode.pop();
	  
	  if (v1 instanceof Boolean) {
		  MyNode.push(! (Boolean)v1 );  
	  } else {
		  throw new Exception("Internal type error");
	  }
  }
}
/* JavaCC - OriginalChecksum=615b8204f6af04fbca6f14dbaeab132f (do not edit this line) */
