/* Generated By:JJTree: Do not edit this line. ASTor.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTor extends SimpleNode {
  public ASTor(int id) {
    super(id);
  }

  public ASTor(Lang p, int id) {
    super(p, id);
  }

  public void run() throws Exception {
	  assert this.jjtGetNumChildren() == 2;
	  for (Node n : this.children) {
		  ((MyNode)n).run();
	  }
	  
	  Object v2 = MyNode.pop();
	  Object v1 = MyNode.pop();
	  
	  if (v1 instanceof Boolean && v2 instanceof Boolean) {
		  MyNode.push((Boolean)v1 || (Boolean)v2);  
	  }
  }
}
/* JavaCC - OriginalChecksum=9337518a026f8b69ec1d808f099eb851 (do not edit this line) */
