/* Generated By:JJTree: Do not edit this line. ASTparams.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTparams extends SimpleNode {
  public ASTparams(int id) {
    super(id);
  }

  public ASTparams(Lang p, int id) {
    super(p, id);
  }

  public void run() throws Exception {
	  int num = this.jjtGetNumChildren();
	  
	  for (int i = num - 1; i >= 0; i--) {
		  ((SimpleNode)this.children[i]).run();
	  }
  }
}
/* JavaCC - OriginalChecksum=c89822fef3cabeb2687c97e1a0e560c6 (do not edit this line) */
