/* Generated By:JJTree: Do not edit this line. ASTprocedure.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTprocedure extends SimpleNode {  
  public ASTprocedure(int id) {
    super(id);
  }

  public ASTprocedure(Lang p, int id) {
    super(p, id);
  }

  public void run() throws Exception {
	  MyNode.open_context();
	  for (Node n:this.children)
		  ((MyNode)n).run();
	  MyNode.close_context();
  }
}
/* JavaCC - OriginalChecksum=72af6f2dff93b75a2d33811571af3522 (do not edit this line) */
