/* Generated By:JJTree: Do not edit this line. ASTreturn_type.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTreturn_type extends SimpleNode {
  public ASTreturn_type(int id) {
    super(id);
  }

  public ASTreturn_type(Lang p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4319fe066a0a4fcc09e466e323c8490b (do not edit this line) */
