/* Generated By:JJTree: Do not edit this line. ASTroutine_param.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTroutine_param extends SimpleNode {
  public ASTroutine_param(int id) {
    super(id);
  }

  public ASTroutine_param(Lang p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=310a355db743914ab69e0a9bdc13401f (do not edit this line) */
