/* Generated By:JJTree: Do not edit this line. ASTswhile.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTswhile extends SimpleNode {
  public ASTswhile(int id) {
    super(id);
  }

  public ASTswhile(Lang p, int id) {
    super(p, id);
  }

  public void run() throws Exception {
	  assert this.jjtGetNumChildren() <= 2;
	  ((MyNode)this.children[0]).run(); //comparaison
	  
	  while ((Boolean)MyNode.pop()) {
		  ((MyNode)this.children[1]).run();
		  ((MyNode)this.children[0]).run(); //comparaison
	  }
  }
}
/* JavaCC - OriginalChecksum=75455a69674d1dfbd0ee695aff3f8a25 (do not edit this line) */
