/* Generated By:JJTree: Do not edit this line. ASTsif.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTsif extends SimpleNode {
  public ASTsif(int id) {
    super(id);
  }

  public ASTsif(Lang p, int id) {
    super(p, id);
  }

  public void run() throws Exception {
	  assert this.jjtGetNumChildren() <= 3;
	  ((MyNode)this.children[0]).run(); //comparaison
	  
	  if ((Boolean)MyNode.pop()) {
		  ((MyNode)this.children[1]).run();
	  } else {
		  if (this.jjtGetNumChildren() == 3)
			  ((MyNode)this.children[2]).run();
	  }
  }
}
/* JavaCC - OriginalChecksum=f8461622b4975c80139fc65b09cdc71f (do not edit this line) */
