/* Generated By:JJTree: Do not edit this line. ASTsroutines.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTsroutines extends SimpleNode {
	
  public ASTsroutines(int id) {
    super(id);
  }

  public ASTsroutines(Lang p, int id) {
    super(p, id);
  }

  public void run() {
	  for (Node n : this.children) {
		  String name = (String)((SimpleNode)n).value;
		  MyNode.routinesTable.put(name, (SimpleNode)n);
	  }
	  //System.out.println(MyNode.routinesTable);
  }
}
/* JavaCC - OriginalChecksum=46c284ebd52d9153219344007549ec55 (do not edit this line) */
