/* Generated By:JJTree: Do not edit this line. ASTStart.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(Lang p, int id) {
    super(p, id);
  }

  public void run() throws Exception {
	  ((MyNode)this.children[0]).run(); // declarations
	  ((MyNode)this.children[2]).run(); // routines
	  ((MyNode)this.children[1]).run(); // instructions
  }
}
/* JavaCC - OriginalChecksum=a0395757353d16e17de45cb9261643b5 (do not edit this line) */
