/* Generated By:JJTree: Do not edit this line. ASTtype.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTtype extends SimpleNode {
  public ASTtype(int id) {
    super(id);
  }

  public ASTtype(Lang p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=198f2f3217489cab7bcd20f3aadf251c (do not edit this line) */
