/* Generated By:JJTree: Do not edit this line. ASTvoid.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTvoid extends SimpleNode {
  public ASTvoid(int id) {
    super(id);
  }

  public ASTvoid(Lang p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b31adec9c8ea3d8e4926fe31aa3a7be4 (do not edit this line) */
