/* Generated By:JJTree: Do not edit this line. ASTvalueLog.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTvalueLog extends SimpleNode {
  public ASTvalueLog(int id) {
    super(id);
  }

  public ASTvalueLog(Lang p, int id) {
    super(p, id);
  }

  public void run() throws Exception {
	  assert this.jjtGetNumChildren() == 1;
	  ((MyNode)this.children[0]).run();
  }
}
/* JavaCC - OriginalChecksum=2c5998db6074a0aa0d06642b3e442e5d (do not edit this line) */
