/* Generated By:JJTree: Do not edit this line. ASTvconst.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=MyNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package grammaireV3;

public
class ASTvconst extends SimpleNode {
  public ASTvconst(int id) {
    super(id);
  }

  public ASTvconst(Lang p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fa757e79be4daad4a4ec229513a47c3d (do not edit this line) */
