/* Generated By:JavaCC: Do not edit this line. LangTreeConstants.java Version 5.0 */
package grammaireV3;

public interface LangTreeConstants
{
  public int JJTSTART = 0;
  public int JJTDECLARATIONS = 1;
  public int JJTVOID = 2;
  public int JJTVARIABLE = 3;
  public int JJTCONSTANT = 4;
  public int JJTTYPE = 5;
  public int JJTIDENT = 6;
  public int JJTINSTRUCTIONS = 7;
  public int JJTAFFECT = 8;
  public int JJTVALUELOG = 9;
  public int JJTVALUE = 10;
  public int JJTCALLPROC = 11;
  public int JJTCALLFUNCT = 12;
  public int JJTARGUMENT = 13;
  public int JJTBOOL = 14;
  public int JJTVCONST = 15;
  public int JJTSIF = 16;
  public int JJTSWHILE = 17;
  public int JJTSROUTINES = 18;
  public int JJTPROCEDURE = 19;
  public int JJTFUNCTION = 20;
  public int JJTRETURN_TYPE = 21;
  public int JJTPARAMS = 22;
  public int JJTPARAM = 23;
  public int JJTOR = 24;
  public int JJTAND = 25;
  public int JJTNOT = 26;
  public int JJTCOMP = 27;
  public int JJTPLUS = 28;
  public int JJTMINUS = 29;
  public int JJTMUL = 30;
  public int JJTDIV = 31;
  public int JJTMIN = 32;
  public int JJTARITH = 33;


  public String[] jjtNodeName = {
    "Start",
    "declarations",
    "void",
    "variable",
    "constant",
    "type",
    "ident",
    "instructions",
    "affect",
    "valueLog",
    "value",
    "callProc",
    "callFunct",
    "argument",
    "bool",
    "vconst",
    "sif",
    "swhile",
    "sroutines",
    "procedure",
    "function",
    "return_type",
    "params",
    "param",
    "or",
    "and",
    "not",
    "comp",
    "plus",
    "minus",
    "mul",
    "div",
    "min",
    "arith",
  };
}
/* JavaCC - OriginalChecksum=d56b488a963f9870e2f682fb9b4d548f (do not edit this line) */
